  version: '3.8'

  services:

    db:
      image: postgres:latest
      container_name: lambda_voyage
      restart: always
      volumes:
        - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        - POSTGRES_DB=lambda_voyage
        - POSTGRES_USER=steep
        - POSTGRES_PASSWORD=lambdavoyage
      ports:
        - "5432:5432"

    cache:
      image: redis:6.2-alpine
      container_name: lambda_voyage_cache
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --loglevel warning --requirepass password

    document-db:
      image: mongo:6.0.4
      restart: always
      container_name: lambda_voyage_users
      environment:
        MONGO_INITDB_ROOT_USERNAME: master
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: users
      ports:
        - "27017:27017"
      volumes:
        - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

